version: '3.7'

services: 
  front_end: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile.develop
    env_file: 
      - ./frontend/frontend.env
    ports: 
      - 3000:3000
    networks: 
      - backend_network
    container_name: frontend
  yesod_app: 
    build: 
      context: ./yesodApp
      dockerfile: Dockerfile.develop
    volumes:
      - type: bind
        source: ./yesodApp/app
        target: /app/app
      - type: bind
        source: ./yesodApp/config
        target: /app/config
      - type: bind
        source: ./yesodApp/src
        target: /app/src
      - type: bind
        source: ./yesodApp/static
        target: /app/static
      - type: bind
        source: ./yesodApp/templates
        target: /app/templates
      - type: bind
        source: ./yesodApp/test
        target: /app/test
    env_file: 
      - ./yesodApp/yesodApp.env
    ports: 
      - 4000:3000
    networks: 
      - backend_network
      - database_network
    container_name: yesodApp
    stdin_open: true
    depends_on:
      - database
  actix:
    build: 
      context: ./actix
    env_file: 
      - ./actix/actix.env
    ports: 
      - 3500:8088
    networks: 
      - backend_network
      - database_network
    container_name: actix
    volumes:
      - type: bind
        source: ./actix/src
        target: /app/src
    depends_on:
      - database
  database:
    image: postgres:12.1
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: yesodApp
      POSTGRES_PASSWORD: yesodApp
    ports:
      - 5432:5432
    networks: 
      - database_network
    container_name: database
  rocket:
    build: 
      context: ./rocket
    env_file: 
      - ./rocket/rocket.env
    ports: 
      - 4500:8000
    networks: 
      - backend_network
      - database_network
    container_name: rocket
    volumes:
      - type: bind
        source: ./rocket/src
        target: /app/src
    depends_on:
      - database

networks:
  backend_network:
  database_network:
